<?php

function queen_attack_menu() {
  $items['queen_attack'] = array(
    'title' => 'Queen Attack',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('queen_attack_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  $items['queen_attack_results_page'] = array(
    'title' => 'Attack?',
    'page callback' => 'queen_attack_result',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function queen_attack_form() {
  $form['queen_latifahs_position1'] = array(
    '#title' => "Queen Latifah's Position",
    '#type' => 'select',
    '#options' => array(1 => 'A', 2 => 'B', 3 => 'C', 4 => 'D', 5 =>'E', 6 => 'F', 7 => 'G', 8 => 'H'),
    '#description' => t("Queen's position (letter):"),
  );

  $form['queen_latifahs_position2'] = array(
    '#type' => 'select',
    '#options' => array(1 => 1,2 => 2,3 => 3,4 => 4,5 => 5,6 => 6,7 => 7,8 => 8),

    '#description' => t("Queen's position (number):"),
  );

  $form['target_position1'] = array(
    '#title' => "Target's Position",
    '#type' => 'select',
    '#options' => array(1 => 'A', 2 => 'B', 3 => 'C', 4 => 'D', 5 =>'E', 6 => 'F', 7 => 'G', 8 => 'H'),
    '#description' => t("Target's position (letter):"),
  );

  $form['target_position2'] = array(
    '#type' => 'select',
    '#options' => array(1 => 1,2 => 2,3 => 3,4 => 4,5 => 5,6 => 6,7 => 7,8 => 8),
    '#description' => t("Target's position (number):"),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Queen Attack?',
  );
  return $form;
}

function queen_attack_form_submit($form, &$form_state) {
  $queen_pos1 = $form_state['values']['queen_latifahs_position1'];
  $queen_pos2 = $form_state['values']['queen_latifahs_position2'];
  $target_pos1 = $form_state['values']['target_position1'];
  $target_pos2 = $form_state['values']['target_position2'];

  if ($queen_pos2 === $target_pos2) {
    $_SESSION['result'] = 'true';
  } elseif ($queen_pos1 === $target_pos1) {
    $_SESSION['result'] = 'true';
  } elseif (abs($queen_pos1-$target_pos1)-abs($queen_pos2-$target_pos2) == 0)  {
    $_SESSION['result'] = 'true';
  }  else {
    $_SESSION['result'] = 'false';
  }

  $form_state['redirect'] = 'queen_attack_results_page';
}

function queen_attack_result() {
  $result = $_SESSION['result'];
  if ($result === 'true') {
    return "Queen Latifah is ready to attack!!";
  } else {
    return "You're in the clear for now, pawn.";
  }
}
