<?php

function queen_attack_menu() {
  $items['queen_attack'] = array(
    'title' => 'Queen Attack',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('queen_attack_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  $items['queen_attack_results_page'] = array(
    'title' => 'Attack?',
    'page callback' => 'queen_attack_result',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function queen_attack_form() {
  $form['queen_latifahs_position'] = array(
    '#title' => "Queen Latifah's Position",
    '#type' => 'textfield',
    '#description' => t('Where is the queen?'),
  );

  $form['target_position'] = array(
    '#title' => "Target Position",
    '#type' => 'textfield',
    '#description' => t('Where is the target piece?'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Queen Attack?',
  );
  return $form;
}

function queen_attack_form_submit($form, &$form_state) {
  $queen_pos = $form_state['values']['queen_latifahs_position'];
  $target_pos = $form_state['values']['target_position'];

  $_SESSION['queen_output'] = $queen_pos;
  $_SESSION['target_output'] = $target_pos;

  $form_state['redirect'] = 'queen_attack_results_page';
}

function queen_attack_result() {
  $result = $_SESSION['queen_output'] . ' ' . $_SESSION['target_output'];
  return 'Results: ' . $result;
}
